In [1]:
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as imr
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.preprocessing import LabelEncoder
import torch

import torch.nn as nn
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torch.utils.data import SubsetRandomSampler
from PIL import Image

Cell below is used because of a bug in converting between I and L in PIL (ibterger to greyscale)

In [108]:
# adapted from https://github.com/python-pillow/Pillow/issues/3011#issuecomment-552141447
def convert_I_to_L(img):
    arrayd = np.uint8(np.array(img) / 256)
    return Image.fromarray(arrayd).convert("L")

In [158]:
# adapted from https://towardsdatascience.com/loading-custom-image-dataset-for-deep-learning-models-part-1-d64fa7aaeca6
dir=Path.cwd() / "Data" 
def create_dataset_PIL(img_folder):
    
    img_data_array=[]
    class_name=[]
    for dir1 in os.listdir(img_folder):
        for file in os.listdir(os.path.join(img_folder, dir1)):
       
            image_path= os.path.join(img_folder, dir1,  file)
            ima=Image.open(image_path)
            print(ima.mode,"   pre")
            if (ima.mode)=='I':
                ima=convert_I_to_L(ima)
            else:
                ima=ima.convert("L")
            print(ima.mode)
            image= np.array(ima.resize((128,128), Image.NEAREST))
            print(image)
            
            image = image.astype('float32')
            
            img_data_array.append(image)
            class_name.append(dir1)
            ima.close()
    return img_data_array , class_name
PIL_img_data, class_name=create_dataset_PIL(dir)

74]
 [ 25  79 125 ... 184 178 174]]
I    pre
L
[[ 17  21  18 ... 200 198 196]
 [ 17  21  17 ... 209 201 199]
 [ 17  22  17 ... 206 204 200]
 ...
 [ 27 107 124 ... 174 174 172]
 [ 30 104 124 ... 171 169 170]
 [ 25  91 125 ... 170 173 171]]
I    pre
L
[[ 16  17  25 ... 193 189 189]
 [ 16  17  25 ... 193 191 190]
 [ 17  19  26 ... 193 191 192]
 ...
 [128 142 161 ... 181 184 170]
 [123 142 161 ... 183 185 171]
 [110 131 160 ... 184 178 180]]
I    pre
L
[[ 16  17  24 ... 192 190 184]
 [ 16  17  24 ... 193 190 191]
 [ 16  19  25 ... 193 190 190]
 ...
 [129 143 161 ... 183 178 182]
 [127 144 159 ... 183 178 185]
 [113 133 161 ... 182 180 180]]
I    pre
L
[[ 16  17  24 ... 191 188 187]
 [ 16  17  23 ... 193 190 193]
 [ 16  18  24 ... 192 191 191]
 ...
 [130 145 161 ... 189 185 183]
 [130 147 160 ... 189 183 181]
 [117 136 163 ... 185 181 177]]
I    pre
L
[[ 17  17  23 ... 189 186 188]
 [ 16  17  23 ... 193 190 190]
 [ 17  17  23 ... 193 191 192]
 ...
 [130 149 161 ... 187 187 181]
 [130 147 16

In [161]:
print(arraytest[0])

[[ 24.  18.  23. ... 183. 182. 182.]
 [ 18.  15.  26. ... 190. 186. 190.]
 [ 16.  15.  26. ... 187. 184. 187.]
 ...
 [ 32.  23. 109. ... 178. 187. 176.]
 [ 29.  22. 102. ... 170. 181. 174.]
 [ 24.  20.  78. ... 172. 183. 172.]]


In [165]:
arraytest=np.asarray(class_name)
#fotograpgh=Image.fromarray(arraytest[0])

In [168]:
arraytest.astype(bytes)

array([b'closed', b'closed', b'closed', ..., b'right', b'right', b'right'],
      dtype='|S6')

In [159]:
fotograpgh= Image.open(dir/ "closed"/ "azharclose (1).png")
fotograpgh=convert_I_to_L(fotograpgh)
fotograpgh=fotograpgh.resize((128,128), Image.NEAREST)
qw=np.array(fotograpgh)
print(qw.shape)
#qw=np.resize(qw,(187,483))
fotograpgh.close()
fotograpgh=Image.fromarray(qw.astype('float32'))
fotograpgh.show()


(128, 128)


In [163]:
fotograpgh.show()

In [169]:
data=np.array(PIL_img_data)
labels = np.array(class_name)
labels=labels.astype(bytes)

In [170]:
np.save("data.npy",data)
np.save("labels.npy",labels)